# Generated by Django 4.2.3 on 2023-07-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_watched_courses_userwatchedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.FloatField(default=0, unique=True),
        ),
    ]
