# Generated by Django 4.2.3 on 2023-07-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_course_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='crn',
            field=models.IntegerField(unique=True),
        ),
    ]
